sudo: false
language: cpp

branches:
  only:
  - master

env:
  global:
    - BIN=qmlonline

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: require
      services: docker
      env: WEBASM="true"

script:
- if [ ! -z "${WEBASM}" ]; then
    git remote set-url origin https://${GITHUB_TOKEN}@github.com/patrickelectric/qmlonline;
    git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*";
    git fetch --all;
    git config --global user.name "Patrick José Pereira";
    git config --global user.email "patrickelectric@gmail.com";
    echo "Build project";
    mkdir build;
    docker run --rm -v $PWD:/project/source -v $PWD/build:/project/build maukalinow/qtwasm_builder:5.13_latest;
    rm -rf build/{Makefile,*.o,*.cpp};
    git checkout --track origin/gh-pages;
    mv build/* .;
    rm -rf build;
    sudo mv qmlonline.html index.html;
    git add --all;
    git commit -sm "Update WebAssembly";
  fi

after_success:
- if [ "$TRAVIS_BRANCH" != "master" ]; then
    echo "$TRAVIS_BRANCH is not master, deploy will not be done.";
    exit 0;
  fi
- if [ ! -z "${WEBASM}" ]; then git push origin gh-pages; fi
